name: test

on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false

      matrix:
        os:
         - macos-14
         - macos-15

        ruby-version:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - ruby-head

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - run: |
          bundle install
          bundle exec exe/md2key # Test only syntax and basic functionality
        continue-on-error: ${{ matrix.ruby-version == 'ruby-head' }}
